version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.22
    - 14.14.24
    - 14.14.25
    - 14.14.26
    - 14.14.28
    - 14.14.30
    - 14.14.31
    - 14.14.32
    - 14.14.33
    - 14.14.34
    - 14.14.35
    - 14.14.36
    - 14.14.37
    - 14.14.39
    - 14.14.41
    - 15.0.0
  - dependency-name: user-agents
    versions:
    - 1.0.563
    - 1.0.565
    - 1.0.566
    - 1.0.570
    - 1.0.571
    - 1.0.573
    - 1.0.574
    - 1.0.577
    - 1.0.579
    - 1.0.580
    - 1.0.584
    - 1.0.586
    - 1.0.587
    - 1.0.588
    - 1.0.591
    - 1.0.592
    - 1.0.594
    - 1.0.598
    - 1.0.600
    - 1.0.601
    - 1.0.605
    - 1.0.606
    - 1.0.607
    - 1.0.609
    - 1.0.612
    - 1.0.614
    - 1.0.616
    - 1.0.617
    - 1.0.620
    - 1.0.621
    - 1.0.623
    - 1.0.628
    - 1.0.630
    - 1.0.631
    - 1.0.634
    - 1.0.635
  - dependency-name: rollup
    versions:
    - 2.38.5
    - 2.39.0
    - 2.39.1
    - 2.40.0
    - 2.41.0
    - 2.41.1
    - 2.41.2
    - 2.41.3
    - 2.41.4
    - 2.41.5
    - 2.42.0
    - 2.42.2
    - 2.42.3
    - 2.42.4
    - 2.43.1
    - 2.44.0
    - 2.45.0
    - 2.45.1
    - 2.45.2
  - dependency-name: browserslist
    versions:
    - 4.16.1
    - 4.16.3
    - 4.16.4
  - dependency-name: eslint
    versions:
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: "@babel/core"
    versions:
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.1
    - 7.13.10
    - 7.13.13
    - 7.13.14
    - 7.13.15
    - 7.13.8
  - dependency-name: size-limit
    versions:
    - 4.10.0
    - 4.10.1
  - dependency-name: typescript
    versions:
    - 4.1.4
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: "@babel/runtime"
    versions:
    - 7.12.13
  - dependency-name: "@trigen/scripts-plugin-eslint"
    versions:
    - 7.0.6
    - 7.3.1
    - 7.3.3
  - dependency-name: "@trigen/scripts-preset-lib"
    versions:
    - 7.0.6
    - 7.3.1
    - 7.3.3
  - dependency-name: "@size-limit/preset-small-lib"
    versions:
    - 4.9.1
    - 4.9.2
  - dependency-name: "@trigen/scripts-plugin-size-limit"
    versions:
    - 7.0.2
    - 7.3.1
  - dependency-name: "@trigen/scripts-plugin-rollup"
    versions:
    - 7.0.2
    - 7.1.0
  - dependency-name: rollup-plugin-typescript2
    versions:
    - 0.29.0
  - dependency-name: "@babel/runtime-corejs3"
    versions:
    - 7.12.5
  - dependency-name: highlight.js
    versions:
    - 10.5.0
